image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - echo "Starting job for ${CI_PROJECT_NAME}"

build:
  stage: build
  script:
    - docker build -t my-image:$CI_COMMIT_REF_SLUG .
  only:
    - master

push:
  stage: push
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker tag my-image:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - master

